// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqst8pFVHlwRyv222ud_EvNf3PlG-2OA',
    appId: '1:174385499981:web:349a49b00cc57f0aceb104',
    messagingSenderId: '174385499981',
    projectId: 'rideproject-92ae0',
    authDomain: 'rideproject-92ae0.firebaseapp.com',
    storageBucket: 'rideproject-92ae0.firebasestorage.app',
    measurementId: 'G-KDJF3XV03B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghekdCWqeMq2JHC6aA_m07C4IWjPxRUY',
    appId: '1:174385499981:android:d7859da7645c4677ceb104',
    messagingSenderId: '174385499981',
    projectId: 'rideproject-92ae0',
    storageBucket: 'rideproject-92ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtoDBXvKA-hPhwm9K8lz9OUZKQJMcNYhU',
    appId: '1:174385499981:ios:50a1730be164a0b5ceb104',
    messagingSenderId: '174385499981',
    projectId: 'rideproject-92ae0',
    storageBucket: 'rideproject-92ae0.firebasestorage.app',
    iosBundleId: 'com.example.rideProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtoDBXvKA-hPhwm9K8lz9OUZKQJMcNYhU',
    appId: '1:174385499981:ios:50a1730be164a0b5ceb104',
    messagingSenderId: '174385499981',
    projectId: 'rideproject-92ae0',
    storageBucket: 'rideproject-92ae0.firebasestorage.app',
    iosBundleId: 'com.example.rideProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdqst8pFVHlwRyv222ud_EvNf3PlG-2OA',
    appId: '1:174385499981:web:7fa6e4852ee1b9e7ceb104',
    messagingSenderId: '174385499981',
    projectId: 'rideproject-92ae0',
    authDomain: 'rideproject-92ae0.firebaseapp.com',
    storageBucket: 'rideproject-92ae0.firebasestorage.app',
    measurementId: 'G-ELQDBHQ0P6',
  );
}
